data:
  students:
    - "第一个文件"
    - "第二个文件"
    - "第三个文件"

## 所有目录的根目录都是运行jar所在的目录
#folders:
#  # 所上传的源文件所在的目录
#  sourceFolder: "sourceFiles"
#  copyFolder: "copyFiles"
#  zipFolder: "zipFiles"
#
fileNames:
  # 配置最终下载的文件名，后缀固定为zip
  downloadFileName: "success"


spring:
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: "HTML"
    encoding: "UTF-8"
    contentType: "text/html"
    cache: false
    spring:
      web:
        resources:
          chain:
            strategy:
              content:
                enabled: true
                paths: "/**"
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      # 设置单个上传的文件大小为20MB
      max-file-size: "20MB"
      # 设置总共上传的文件大小为20MB
      max-request-size: "20MB"

server:
  tomcat:
    access-log:
      encoding: "UTF-8"
  port: 26881


